logging:
    level:
        ROOT: INFO
        com.querydsltips.filtering: DEBUG

spring:
    profiles:
        active: dev

    devtools:
        restart:
            enabled: true

    jackson:
        serialization.indent_output: true

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CET
        username: root
        password: root

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        show-sql: true
        properties:
            hibernate:
                type: trace
                format_sql: true
                use_sql_comments: true

    liquibase:
      contexts: dev